
export const INCREMENT='INCREMENT'
export const DECREMENT='DECREMENT'
export const ADD='ADD'
export const SUB='SUB'
export const ADDSTORERESULTS='ADDSTORERESULTS'
export const REMOVESTORERESULTS='REMOVESTORERESULTS'
